build:
    environment:
        php: '5.5.12'

filter:
    paths:
        - 'src/Grapevine/*'

checks:
    php:
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        classes_in_camel_caps: true
        avoid_superglobals: true
        avoid_usage_of_logical_operators: true
        blank_line_after_namespace_declaration: true
        encourage_shallow_comparison: true
        ensure_lower_case_builtin_functions: true
        fix_doc_comments: true
        fix_identation_4spaces: true
        fix_linefeed: true
        fix_php_opening_tag: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        function_in_camel_caps: true
        instanceof_class_exists: true
        lowercase_basic_constants: true
        lowercase_php_keywords: true
        no_elseif_statements: true
        no_eval: true
        no_exit: true
        no_global_keyword: true
        no_goto: true
        no_short_method_names:
            minimum: '4'
        one_class_per_file: true
        psr2_switch_declaration: true
        psr2_class_declaration: true
        psr2_control_structure_declaration: true

tools:
    external_code_coverage: true
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    sensiolabs_security_checker: true
    php_cpd: true
    php_changetracking: true
